name: Notebook-Tests--Against-Last-Release

on:
  pull_request:
    branches:
    - master

jobs:
  run-perf-test:
    runs-on: 'vs2017-win2016'

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    
    - name: Upgrade pip, setuptools, and wheel before installing other dependencies
      run: python -m pip install --upgrade pip setuptools wheel

    - run: pip install -r requirements.txt
      name: 'Install required packages'
      shell: bash
    
    - run: pip install fairlearn
      name: 'Install last released version of Fairlearn'
      shell: bash

    - run: python -m pytest -s ./test/notebooks --junitxml=./TEST.xml
      name: 'Run notebook tests'
      shell: bash

    - name: 'Publish Test Results ./TEST.xml'
      uses: actions/upload-artifact@v1
      with:
        name: results
        path: ./TEST.xml
